# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /
title: Nitesh Mishra
author: Nitesh Mishra
description: Personal blog and resume
avatar: nitesh.png
email: nitesh.mishra143@gmail.com
github: nitesh-mishra 
twitter: 007niteshMishra
linkedin: nitesh-mishra-12057356
stackoverflow: users/4201837/nitesh-mishra   #e.g: users/2735833/proton1h1
facebook: nitesh.mishra.5855594
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
